
name: NichiSkyBlock
author: BaliGamerz\MadeAja
website: http://github.com/MadeAja
main: BaliGamerz\SkyBlock\Main
version: "17 Official Release"
api: 3.0.0

commands:
   mana:
     description: Buy a mana command
   visit:
     description: Visit island
   buyisland:
    description: Buy a island theme
   score:
    description: Scoreud options command
   join:
    description: Join a you island
   buy:
    description: Skyblock shops
   addquest:
    description: Add quests command
    permission: quests.add.use


permissions:
    sbpe.cmd.help:
     default: true
     description: Allows player to see all the SkyBlock commands.
    sbpe.cmd.create:
     default: true
     description:  Allows players to create an island
    sbpe.countdown.bypass:
     default: op
     description: Bypass countdown create island
    sbpe.category.bypass:
     default: op
     description: Bypass shop
    sbpe.cmd.join:
     default: true
     description: go to your island
    sbpe.cmd.kick:
     default: true
     description: Kick someone off your island
    sbpe.cmd.lock:
     default: true
     description: Lock people from going to your island
    sbpe.cmd.sethome:
     default: true
     description: Sethome on your island
    sbpe.cmd.home:
     default: true
     description: Go to your island home
    sbpe.cmd.members:
     default: true
     description: List of members on your island.
    sbpe.cmd.tp:
     default: true
     description: Teleport to an unlocked island
    sbpe.cmd.optp:
     default: op
     description: Teleport to any island with someone online
    sbpe.cmd.invite:
     default: true
     description: Invite a player to your island
    sbpe.cmd.invite.accept:
     default: true
     description: Accept an invite
    sbpe.cmd.invite.reject:
     default: true
     description: Reject an invite
    sbpe.cmd.leave:
     default: true
     description: leave your island
    sbpe.cmd.remove:
     default: true
     description: Delete your island
    sbpe.cmd.makeleader:
     default: true
     description: make someone else the leader of your island







