#               Copyright (C) 2016 MadeAja/BaliGamerz
##    ███╗░░░███╗░█████╗░██████╗░███████╗░█████╗░░░░░░██╗░█████╗░
##    ████╗░████║██╔══██╗██╔══██╗██╔════╝██╔══██╗░░░░░██║██╔══██╗
##    ██╔████╔██║███████║██║░░██║█████╗░░███████║░░░░░██║███████║
##    ██║╚██╔╝██║██╔══██║██║░░██║██╔══╝░░██╔══██║██╗░░██║██╔══██║
##    ██║░╚═╝░██║██║░░██║██████╔╝███████╗██║░░██║╚█████╔╝██║░░██║
##    ╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═════╝░╚══════╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝
---

#Keep Player Inventory
keep-inventory: true

island:
  max_members: 1
  creation-time: 600
  max-bank-tier: 10
  island_border: 100
  border_message: "Cannot build here"
  sign:
    - "Welcome"
    - "Nichi SkyBlock"
    - "   "
    - "Enjoy"

user:
  max-mana: 2000
  mana_price: 10000

bossbar: true

#Category size
CategoryByBlocks:
  XS: 1000
  S: 200000
  M: 3000000
  L: 4000000000
  XL: 5000000000

#islandLevelBlocks:
#  "ID BLOCK:ID META": Efficiency
#  "2:0": 5

islandLevelBlocks:
  "57:0": 100
  "22:0": 2
  "133:0": 20
  "42:0": 3
  "173:0": 1


hud:
  enable: true
  format: "§c{health}/{max_health} Health   §a{defense} Defense   §b{mana} Mana"

# Enabled Scored
scorehud: true

# 3 seconds update scores
update-score: 3

# Set the timezone for {time} to your own preference.
# false - Follow the server/machine time without changes.
# For a list of timezones you can visit: https://secure.php.net/manual/timezones.php
# Example
#timezone: "America/New_York" - This will set NewYork's time.
timezone: false

# Set the time format that you want to display. Will only work if you add {time} in score-lines in data.yml.
# H - hours
# i - minutes
# s - seconds
# You can fine more information regarding it here: http://php.net/manual/function.date.php
time-format: "H:i:s"

# Set the date format that you want to display. Will only work if you add {date} in score-lines in data.yml.
# d - date (01-31)
# m - month (01-12)
# Y - year (yyyy)
# You can fine more information regarding it here: http://php.net/manual/function.date.php
date-format: "d-m-Y"

sort: 0
titles:
  - "§e§lSKYBLOCK §bCO-OP"
    # {name}                    - Name of the player.
    # {money}                   - Money of the player. (Requires EconomyAPI by poggit-orphanage).
    # {online}                  - The number of online players.
    # {max_online}              - Max number of players allowed on the server.
    # {rank}                    - Players current in-game rank/group. (Requires PurePerms by poggit-orphanage).
    # {item_name}               - Name of the item in players hand.
    # {item_id}                 - ID of the item in players hand.
    # {item_meta}               - Meta/Damage of the item in players hand.
    # {item_count}              - Amount of item in the players hand.
    # {x}/{y}/{z}               - X/Y/Z coordinate of the player.
    # {faction}                 - Faction of the player. (Requires FactionsPro by poggit-orphanage).
    # {faction_power}           - Power of the faction. (Requires FactionsPro by poggit-orphanage).
    # {load}                    - Current load on the server (0 - 100%)
    # {tps}                     - TPS of the server.
    # {level_name}              - Name of the players current level/world.
    # {level_folder_name}       - Folder name of the players current level/world.
    # {ip}                      - IP of the player.
    # {ping}                    - Ping of the player.
    # {time}                    - Show the current time. Please see 'time-format' and 'timezone' in config.yml to modify it.
    # {date}                    - Show the current date. Please see 'date-format' in config.yml to modify it.
    # {sky_name}              - Show Island SkyBlock name
    # {sky_owner}     - Show Owner of skyblock
    # {sky_mine}               - Show mine SkyBlock
    # {sky_level}               - Show Level SkyBlock
    # {size_name}               - Show Size SkyBlock with name
    # {size_int}                - Showing Size SkyBlock with integer
    # {random_color}            - Add color random
    # {sky_member_online}      - Count all members online in your island
    # {sky_allMember}          - Count All member island
    # {sky_progress_int}          - Progress count
    # {sky_progress_size}          - Size of progress
  # {sky_progress}          - Show statistic progress bar
  # {objective_progress}     - Show running quests
lines:
  - "§7{date}"
  - "         "
  - "§fProgress: §b{sky_progress_int}§7/§a{sky_progress_size}"
  - "§7[{sky_progress}§7]"
  - "       "
  - "§fPurse: §6{money}"
  - "          "
  - "§fObjectives: "
  - "§e{objective}"
  - "{objective_progress}"
  - "           "
  - "§eplay.nichiwa.net"
...